### PR TITLE
Introduced NLog.Extensions.AzureEventGrid

### PR DESCRIPTION
**Pull request by snakefoot**
See also: https://learn.microsoft.com/en-us/azure/event-grid/compare-messaging-services

Service | Purpose | Type | When to use
-- | -- | -- | --
Event Grid | Reactive programming | Event distribution (discrete) | React to status changes
Event Hubs | Big data pipeline | Event streaming (series) | Telemetry and distributed data streaming
Service Bus | High-value enterprise messaging | Message | Order processing and financial transactions

Seems batching is seldom used for "Event Grid" as it requires the receiver to also keep up.

https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/45346675/artifacts

### CODE REVIEW

**Comment by snakefoot** [comment]
@JDetmar Also ready for review

**Comment by JDetmar** [comment]
@snakefoot everything looks good, I have not had a chance to try it out. If you feel it's good I will merge it. I don't want to block just because I didn't try it out.

**Comment by snakefoot** [comment]
@JDetmar I'm not in a hurry. Just thought it would be nice to support all 3 messaging services.

**Comment by snakefoot** [comment]
Updated to ver. 4 using latest Azure.Identity

**Comment by snakefoot** [comment]
@JDetmar Ready for merge, and initial nuget-publish

**Pull request merged**
