### PR TITLE
NLog.Extensions.AzureEventHub - Initial Version

### PR DESCRIPTION
**Pull request by snakefoot**
@JDetmar It compiles. Unit tests are green. But have no Azure Cloud to actual test if it works :)

### CODE REVIEW

**Comment by snakefoot** [comment]
Nuget-package available for testing:

https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/27002472/artifacts

**Comment by JDetmar** [comment]
Looks good so far in my testing.

**Comment by snakefoot** [comment]
Happy to hear. Will make a new PR with example config in Readme.md and link to nuget:


https://www.nuget.org/packages/NLog.Extensions.AzureEventHub/


Will also look into updating the other NLog targets to use AsyncTaskTarget and depend on NLog 4.6.5


Sent from my Sony Xperia


---- Justin Detmar wrote ----


Looks good so far in my testing.

**Comment by JDetmar** [comment]
> Will also look into updating the other NLog targets to use AsyncTaskTarget and depend on NLog 4.6.5

Yes, that will be a nice update.
I noticed that you took the 4.6.5 dependency here to have that.

**Comment by snakefoot** [comment]
Created #40 with update of Readme.md

**Pull request merged**
