### PR TITLE
Renamed projects to match name of NLog target

### PR DESCRIPTION
**Pull request by snakefoot**
When I created the sub-projects then I wanted them to include the "AzureStorage" in their project-name.

But I think it is better that the assembly-name matches the target-name used in Nlog-config (One to one relationship between assembly-name in `<extensions>` and targe-type-name).

### CODE REVIEW

**Comment by snakefoot** [comment]
If accepted. Then I will update the Readme.md to include the new nuget-package-names.

**Comment by JDetmar** [comment]
Yeah, I think that is right. I question the original targets names I created and if they could have been better matching what Microsoft uses. 
Like AzureStorageBlob
Now that we are here I think this proposal makes sense.

**Comment by snakefoot** [comment]
So change target-symbol-name to  `AzureStorageBlob` or change assembly-package to `AzureBlobStorage` ?

Btw. Microsoft calls it self "Microsoft Azure Blob Storage"

**Comment by JDetmar** [comment]
I think to stick to your proposed

> change assembly-package to AzureBlobStorage

**Comment by JDetmar** [comment]
I should have checked first, but there is a package name collision
https://www.nuget.org/packages/NLog.Extensions.AzureTableStorage

**Comment by snakefoot** [comment]
How unfortunate. Not sure if it will be easy to take over the naming.

Guess we need to spinup an idea engine, and reconsider the target-name.

What about:
- NLog.Extensions.AzureDbTableStorage - Maybe too generic?
- NLog.Extensions.AzureDatabaseStorage - Maybe too generic?
- NLog.Extensions.AzureCosmoTableStorage - https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table
- NLog.Extensions.AzureCosmoDbStorage - https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table
- NLog.Extensions.AzureDocumentDbStorage - https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core/ (Dependency of Microsoft.Azure.Cosmos.Table-package)

Also think I have misunderstood something when creating the azure-tables-storage-project. Looks like the CosmoDb is a much more expensive solution, but they just have a similar API to Azure Table Storage. The correct package for the cheap-ass Azure Table Storage should still be the [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage/)-package. See also: https://docs.microsoft.com/en-us/azure/cosmos-db/table-support?toc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fstorage%2Ftables%2FTOC.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fazure%2Fbread%2Ftoc.json#developing-with-azure-table-storage

Or are you able to use the 2.0.0-preview to communicate with Azure Table Storage?

**Comment by JDetmar** [comment]
> Or are you able to use the [2.0.0-preview](https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/27260409/artifacts) to communicate with Azure Table Storage? If not then maybe two packages need to be created:
>
> * NLog.Extensions.AzureStorage - Depends on WindowsAzure.Storage-package
> * NLog.Extensions.AzureCosmoTableStorage - Depends on Microsoft.Azure.Cosmos.Table-package

I think the two packages can make sense. I will have to test to see if that [2.0.0-preview](https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/27260409/artifacts)  works. From everything I am reading it isn't exactly clear.

**Comment by JDetmar** [comment]
I was successful in using [Microsoft.Azure.Cosmos.Table](https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table/1.0.4) to write to both Azure Storage Account Tables and Azure Cosmos DB as it is implemented in [2.0.0-preview](https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/27260409/artifacts). 

New name NLog.Extensions.AzureCosmosTableStorage ?

**Comment by snakefoot** [comment]
Yes I like that namr. Will create a PR tonight with the change to the new name.


Sent from my Sony Xperia


---- Justin Detmar wrote ----


I was successful in using Microsoft.Azure.Cosmos.Table<https://www.nuget.org/packages/Microsoft.Azure.Cosmos.Table/1.0.4> to write to both Azure Storage Account Tables and Azure Cosmos DB as it is implemented in 2.0.0-preview<https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/27260409/artifacts>.

New name NLog.Extensions.AzureCosmosTableStorage ?

**Pull request merged**
