### PR TITLE
Fix error on DataTable

### PR DESCRIPTION
**Pull request by m4ss1m0g**
The error  prevent to write to table if already exist

### CODE REVIEW

**Comment by m4ss1m0g** [comment]
This pull request close the #110

**Comment by snakefoot** [comment]
Thank you so much for this pull-request. Believe the same fix is included with the existing #111

**Comment by m4ss1m0g** [comment]
Yes indeed the #111 fix the same issue. How long do you plan to release the new version?

**Comment by snakefoot** [comment]
> How long do you plan to release the new version?

When @JDetmar decides to push the merge-button :)

**Comment by JDetmar** [comment]
now available https://www.nuget.org/packages/NLog.Extensions.AzureDataTables/3.1.0

**Pull request closed without merging**
