### PR TITLE
Changed to Azure.Messaging.EventHubs ver. 5.5.0

### PR DESCRIPTION
**Pull request by snakefoot**
I guess someone should volunteer to test if the new version of `NLog.Extensions.AzureEventHub.3.0.0.nupkg` is working :)

Nuget-packages: https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/39978672/artifacts

### CODE REVIEW

**Comment by snakefoot** [comment]
@adrianignat13 [Microsoft.Azure.EventHubs](https://www.nuget.org/packages/Microsoft.Azure.EventHubs/) is now registered as legacy, and Microsoft now recommends that one should move to [Azure.Messaging.EventHubs](https://www.nuget.org/packages/Azure.Messaging.EventHubs)

If you have some spare time, then it would be very helpful if you could take this [pre-release-build](https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/38409033/artifacts) (`NLog.Extensions.AzureEventHub.3.0.0.nupkg`) for a test-drive. Since you seem to require full speed and will be a good smoke test.

**Comment by snakefoot** [comment]
Look like my hack to reduce memory-allocation has been [dicovered and wil be blocked](https://github.com/Azure/azure-sdk-for-net/pull/19876). Hopefully they will [fix the leak](https://github.com/Azure/azure-sdk-for-net/pull/19876) so the hack is not needed :)

**Comment by jsquire** [comment]
> Looks like my hack to reduce memory-allocation has been [dicovered and wil be blocked](https://github.com/Azure/azure-sdk-for-net/pull/19873). Hopefully they will [fix the leak](https://github.com/Azure/azure-sdk-for-net/pull/19876) so the hack is not needed :)

The linked pull request is not a breaking change; it only hides the constructor from code completion and improves documentation to clarify the intent.  The hack that is in use today will continue to work going forward.   Though, we do intend on including the lazy allocation enhancement in our next release as well, which should obviate the need to hack around it.

**Comment by snakefoot** [comment]
@jsquire Yes learning something new today as a library-developer. Didn't know about `System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]` 

Anyway moved to `EventHubsModelFactory.EventData` as recommended.

**Comment by jsquire** [comment]
> @jsquire Yes learning something new today as a library-developer. Didn't know about `System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Never)]`. One might consider adding `obsolete`-attribute to guide existing users away from the constructor aswell.
> 
> Anyway moved to `EventHubsModelFactory.EventData` as recommended.

No worries;  I just wanted to make the intent clear.   :smile: 

We have a strict "no breaking changes" policy outside of exceptional cases.  Even use of `[Obsolete]` would violate that and introduce warnings that may break existing builds if "warnings as errors" is enabled.  Unless there's a security consideration or another factor that puts developers at risk, a soft deprecation via hiding is the approach that the Azure SDKs take.

**Comment by snakefoot** [comment]
Maybe wait for this https://github.com/Azure/azure-sdk-for-net/issues/20105 before making the move (Reintroduces ContentType + CorrelationId)

**Comment by admsteck** [comment]
FYI, Azure/azure-sdk-for-net#20105 has been closed.

**Comment by jsquire** [comment]
> FYI, [Azure/azure-sdk-for-net#20105](https://github.com/Azure/azure-sdk-for-net/issues/20105) has been closed.

I'm happy to say that this is available in the 5.5.0 release, which was just published to [NuGet](https://www.nuget.org/packages/Azure.Messaging.EventHubs/5.5.0)

**Comment by snakefoot** [comment]
Have updated the pull-request to build against ver. 5.5.0 and nuget-packages are available for testing here:

https://ci.appveyor.com/project/JDetmar/nlog-extensions-azurestorage/builds/39978672/artifacts

**Review by JDetmar — APPROVED** [review]

**Pull request merged**
